# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seleccionarProveedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 300)
        self.selectProveedor = QtWidgets.QComboBox(Dialog)
        self.selectProveedor.setGeometry(QtCore.QRect(155, 170, 340, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.selectProveedor.setFont(font)
        self.selectProveedor.setObjectName("selectProveedor")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(185, 100, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Seleccione proveedor"))
